"""empty message

Revision ID: f26c2ea526e3
Revises: bacdd3fe617e
Create Date: 2022-07-08 18:03:38.365568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26c2ea526e3'
down_revision = 'bacdd3fe617e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_name', sa.String(length=200), nullable=True),
    sa.Column('checklist_favorited', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('task_checked', sa.Boolean(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('checklists')
    # ### end Alembic commands ###
